version: '4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafkaBroker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkaBroker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaBroker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_LOG_RETENTION_HOURS: 168


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8086:8080"
    depends_on:
      - kafkaBroker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaBroker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: 'true'

##Eureka Discovery Server
  discovery-server:
    image: rdfgujjar/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      -zipkin

## api-gateway
  api-gateway:
    image: rdfgujjar/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    expose:
      - "8181"
    depends_on:
      - discovery-server

## Prodcut service
  product-service:
    image: rdfgujjar/product-service:latest
    container_name: product-service
    depends_on:
      - discovery-server
      - api-gateway

## order service
  order-service:
      image: rdfgujjar/order-service:latest
      container_name: order-service
      depends_on:
        - discovery-server
        - api-gateway
        - kafkaBroker

## inventory service
  inventory-service:
    image: rdfgujjar/inventory-service:latest
    container_name: inventory-service
    depends_on:
      - discovery-server
      - api-gateway

## notification service
  notification-service:
    image: rdfgujjar/notification-service:latest
    container_name: notification-service
    depends_on:
      - discovery-server
      - api-gateway
      - kafkaBroker








